---
version: 2
models:
  - name: new_etl
    config:
      materialized: incremental
      incremental_strategy: merge
      unique_key: subscription_id
      partition_by: created_date
      schema: presto
      tags: [daily]
    meta:
      owner: '@zaur.ayralov'
